---

- name: Create influxdb apps directory
  sudo: yes
  file:
    path: "{{influxdb_apps_dir}}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download version
  sudo: yes
  command: "wget {{influxdb_dl_url}}"
  args:
    chdir: "{{influxdb_apps_dir}}/"
  changed_when: False
  tags:
    - influxdb

- name: Install package
  sudo: yes
  command: "dpkg --skip-same-version -i {{influxdb_apps_dir}}/influxdb_{{influxdb_ver}}_amd64.deb"
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  notify: restart influxdb
  tags:
    - influxdb

- name: Copy config file
  sudo: yes
  template:
    src: conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
  notify: restart influxdb
  tags:
    - influxdb
