---

- name: Create influxdb apps directory
  sudo: yes
  file:
    path: "{{influxdb_apps_dir}}"
    state: directory
    mode: 0755
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_user}}"

- name: Download version
  get_url:
    url: "{{influxdb_dl_url}}"
    dest: "{{influxdb_pkg}}"
    sha256sum: "{{influxdb_sha_sum}}"
  tags:
    - influxdb

- name: Install package
  command: dpkg --skip-same-version -i {{influxdb_pkg}}
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  tags:
    - influxdb
